export const siteConfig = {
  name: 'Abhishek Shukla',
  title: 'Operations & Customer Experience Consultant',
  tagline: 'Driving Operational Excellence, 10X GenAI Productivity, and Strategic Career Growth',
  bio: 'With 6+ years of specialized experience optimizing performance infrastructure across high-demand sectors like travel, aviation, and digital marketplaces, I translate operational complexity into pure margin protection.',
  email: 'abhishekshukla16102000@gmail.com',
  phone: '8860220070',
  location: 'Delhi, India (Available Globally)',
  domain: 'abhishekshukla.com',
  resumeUrl: '/Abhishek_Shukla_Service_Catalog_Updated.pdf',
  profileImage: '/profile_image.jpeg',
  social: {
    linkedin: 'https://linkedin.com/in/abhishek-shukla-cx',
    twitter: 'https://twitter.com/abhishekshukla',
    instagram: 'https://www.instagram.com/abhishek.cxo/',
    youtube: 'https://youtube.com/@abhishekshukla',
    freelancer: 'https://www.freelancer.com/u/abhishekshukla',
    jobbers: 'https://www.jobbers.com/abhishekshukla',
  },
  hero: {
    greeting: 'Hello, I\'m',
    name: 'Abhishek Shukla',
    subtitle: 'Operations & Customer Experience Consultant',
    description: 'Driving Operational Excellence, 10X GenAI Productivity, and Strategic Career Growth.',
    cta1: { text: 'View My Services', href: '#work' },
    cta2: { text: 'Let\'s Connect', href: '#contact' },
  },
  about: {
    title: 'About Me',
    paragraphs: [
      'With 6+ years of specialized experience optimizing performance infrastructure across high-demand sectors like travel, aviation, and digital marketplaces, I translate operational complexity into pure margin protection.',
      'As an operational partner managing cross-functional programs on platforms like Freelancer.com, I actively guide multi-client voice and non-voice operations. My implementations consistently sustain a Service Level above 95.5% using predictive real-time monitoring, keep First Call Resolution > 85%, and lower Average Handling Time by 15% through strict workflows and root cause analysis.',
      'I specialize in integrating modern Generative AI frameworks into legacy corporate architectures. By automating manual reporting flows, systemizing AI-enabled ticketing networks, and leveraging Microsoft 365 Copilot, I help organizations unlock a 10X boost in team productivity.',
    ],
    philosophy: 'Unlocking a 10X boost in team productivity by replacing operational overhead with scaling output capacity.',
    stats: [
      { label: 'Years Experience', value: '6+' },
      { label: 'Service Level', value: '95.5%+' },
      { label: 'FCR', value: '> 85%' },
      { label: 'AHT Reduction', value: '15%' },
    ],
  },
  work: {
    title: 'Consulting & Services',
    subtitle: 'Professional services tailored to optimize your business operations or accelerate your career track.',
    items: [
      {
        title: 'Operations & Management Consulting',
        category: 'Consulting ($40.00/hr)',
        description: 'Eliminating systemic operational bottlenecks and stabilizing multi-client workflows through project leadership and process auditing.',
        tags: ['Resource Scheduling', 'Process Auditing', 'SOPs', 'Ticketing Layers'],
        link: '#',
        icon: 'Users',
      },
      {
        title: 'Data Reporting & Analytics',
        category: 'Consulting ($40.00/hr)',
        description: 'Converting fragmented raw datasets into crystal-clear automated performance intelligence and MIS Dashboards.',
        tags: ['MIS Dashboards', 'Governance Reporting', 'SLA/QA Metrics'],
        link: '#',
        icon: 'Cpu',
      },
      {
        title: 'Career Guidance & Job Strategy',
        category: 'Coaching ($45.00/hr)',
        description: 'Navigating competitive landscapes using modern platform architecture and targeted roadmaps. Strategic skill mapping and profile structuring.',
        tags: ['Strategic Skill Mapping', 'LinkedIn Optimization', 'Profile Structuring'],
        link: '#',
        icon: 'BookOpen',
      },
      {
        title: 'Custom Interview Prep & Coaching',
        category: 'Coaching ($45.00/hr)',
        description: 'Equipping you with structured confidence to turn incoming interviews into concrete contract wins using targeted question banks and the STAR method.',
        tags: ['Targeted Question Banks', 'STAR Method', 'Live Mock Runs'],
        link: '#',
        icon: 'Award',
      },
    ],
  },
  process: {
    title: 'How I Work',
    subtitle: 'A proven methodology that delivers results.',
    steps: [
      { number: '01', title: 'Discover', description: 'Deep-dive into current operations, pain points, and stakeholder needs through data analysis and empathetic listening.' },
      { number: '02', title: 'Plan', description: 'Design a strategic roadmap combining AI, automation, and lean principles tailored to your unique challenges.' },
      { number: '03', title: 'Build', description: 'Implement solutions with agile methodology, ensuring continuous alignment with business objectives.' },
      { number: '04', title: 'Test & Refine', description: 'Rigorously test, measure KPIs, and iterate based on real-world feedback and data insights.' },
      { number: '05', title: 'Deliver', description: 'Deploy optimized workflows and empower teams with training, documentation, and ongoing support.' },
    ],
  },
  expertise: {
    title: 'Expertise & Certifications',
    subtitle: 'Core competencies and professional certifications.',
    skills: [
      { name: 'AI in Operations', level: 95, category: 'Technology' },
      { name: 'Customer Experience (CX)', level: 98, category: 'Leadership' },
      { name: 'Lean Six Sigma', level: 92, category: 'Methodology' },
      { name: 'M365 Copilot & Power Platform', level: 90, category: 'Technology' },
      { name: 'Process Automation (RPA)', level: 88, category: 'Technology' },
      { name: 'Workforce Management', level: 95, category: 'Operations' },
      { name: 'Data Analytics & BI', level: 85, category: 'Technology' },
      { name: 'Change Management', level: 93, category: 'Leadership' },
      { name: 'Stakeholder Engagement', level: 96, category: 'Leadership' },
      { name: 'Training & Development', level: 90, category: 'Leadership' },
    ],
    certifications: [
      'The AI-Driven Project Manager (LinkedIn Learning)',
      'Agile Project Management (PMI Knowledge Systems)',
      'Customer Experience Leadership (5PHD Aviation Summit)',
      'Generative AI Certified - Support Workflows',
      'Diploma in Travel & Tourism Management (Skylark)',
      'Lean Six Sigma White Belt - Process Optimization',
      'Customer Experience (CX) for Business Success',
      'Microsoft 365 Copilot & Effective Leadership (HP)',
      'Inbound HubSpot Certification',
    ],
  },
  contact: {
    title: 'Let\'s Connect',
    subtitle: 'Ready to optimize your business operations or accelerate your career track? Reach out directly to schedule your primary consultation strategy session today.',
    cta: 'Get In Touch',
  },
  navLinks: [
    { label: 'About', href: '#about' },
    { label: 'Services', href: '#work' },
    { label: 'Process', href: '#process' },
    { label: 'Expertise', href: '#expertise' },
    { label: 'Contact', href: '#contact' },
  ],
} as const;
