export const siteConfig = {
  name: 'Abhishek Shukla',
  title: 'CX & AI Project Leader | Author',
  tagline: 'Driving Operational Excellence, 10X GenAI Productivity, and Strategic Career Growth',
  bio: 'With 7+ years of specialized experience optimizing performance infrastructure across high-demand sectors like travel, aviation, and digital marketplaces, I translate operational complexity into pure margin protection.',
  email: 'abhishekshukla16102000@gmail.com',
  phone: '8860220070',
  location: 'Delhi, India (Available Globally)',
  domain: 'abhishekshukla.com',
  resumeUrl: '/Abhishek_Shukla_Resume.pdf',
  profileImage: '/profile_main.png',
  social: {
    linkedin: 'https://linkedin.com/in/abhishek-shukla-cx',
    twitter: 'https://x.com/Abhishek1610200',
    instagram: 'https://www.instagram.com/cxai.leader?igsh=ZzUzMDNod3l3cTRq',
    youtube: 'https://www.youtube.com/@CXAILeader',
    thinkers360: 'https://www.thinkers360.com/tl/AbhishekShuklaCXandAILeader',
    freelancer: 'https://www.freelancer.com/u/abhishekshukla',
    jobbers: 'https://www.jobbers.com/abhishekshukla',
  },
  hero: {
    greeting: 'Hello, I\'m',
    name: 'Abhishek Shukla',
    subtitle: 'CX & AI Project Leader | Author',
    description: 'Driving Operational Excellence, 10X GenAI Productivity, and Strategic Career Growth.',
    cta1: { text: 'View My Services', href: '#work' },
    cta2: { text: 'Let\'s Connect', href: '#contact' },
  },
  about: {
    title: 'About Me',
    paragraphs: [
      'CX & AI Project Leader with 7+ years of experience leading large-scale voice and non-voice customer operations across travel, airline, and customer support environments. Proven track record of delivering service excellence, improving customer journeys, and driving operational performance through data, technology, AI, and people leadership.',
      'Strong expertise across SLA, AHT, FCR, QA, CSAT, productivity, customer retention, WFM, capacity planning, resource optimization, stakeholder management, and performance governance.',
      'Experienced in leading CX and AI-enabled transformation initiatives, including workflow optimization, CRM and technology integration, AI-assisted customer support, process automation, and digital customer experience improvements. Skilled at translating business challenges into structured project plans and partnering with cross-functional teams to deliver measurable outcomes.',
      'Proven ability to lead teams, manage complex escalations, conduct Root Cause Analysis (RCA) and Corrective and Preventive Actions (CAPA), and improve operational efficiency, productivity, and cost effectiveness.',
      'Strong experience in WBR, MBR, and QBR governance, executive stakeholder communication, reporting, compliance, and continuous improvement, with a leadership approach centered on customer-centricity, innovation, AI adoption, trust, and high-performing teams.',
      'My professional focus is at the intersection of Customer Experience, AI, Leadership, and Business Transformation—helping organizations use technology intelligently while keeping people and customer outcomes at the center.',
    ],
    philosophy: 'Unlocking a 10X boost in team productivity by replacing operational overhead with scaling output capacity.',
    stats: [
      { label: 'Years Experience', value: '7+' },
      { label: 'Service Level', value: '95.5%+' },
      { label: 'FCR', value: '> 85%' },
      { label: 'AHT Reduction', value: '15%' },
    ],
  },
  work: {
    title: 'Consulting & Services',
    subtitle: 'Professional services tailored to optimize your business operations or accelerate your career track.',
    items: [
      {
        title: 'Operations & Management Consulting',
        category: 'Consulting ($40.00/hr)',
        description: 'Eliminating systemic operational bottlenecks and stabilizing multi-client workflows through project leadership and process auditing.',
        tags: ['Resource Scheduling', 'Process Auditing', 'SOPs', 'Ticketing Layers'],
        link: '#',
        icon: 'Users',
      },
      {
        title: 'Data Reporting & Analytics',
        category: 'Consulting ($40.00/hr)',
        description: 'Converting fragmented raw datasets into crystal-clear automated performance intelligence and MIS Dashboards.',
        tags: ['MIS Dashboards', 'Governance Reporting', 'SLA/QA Metrics'],
        link: '#',
        icon: 'Cpu',
      },
      {
        title: 'Career Guidance & Job Strategy',
        category: 'Coaching ($45.00/hr)',
        description: 'Navigating competitive landscapes using modern platform architecture and targeted roadmaps. Strategic skill mapping and profile structuring.',
        tags: ['Strategic Skill Mapping', 'LinkedIn Optimization', 'Profile Structuring'],
        link: '#',
        icon: 'BookOpen',
      },
      {
        title: 'Custom Interview Prep & Coaching',
        category: 'Coaching ($45.00/hr)',
        description: 'Equipping you with structured confidence to turn incoming interviews into concrete contract wins using targeted question banks and the STAR method.',
        tags: ['Targeted Question Banks', 'STAR Method', 'Live Mock Runs'],
        link: '#',
        icon: 'Award',
      },
    ],
  },
  process: {
    title: 'How I Work',
    subtitle: 'A proven methodology that delivers results.',
    steps: [
      { number: '01', title: 'Discover', description: 'Deep-dive into current operations, pain points, and stakeholder needs through data analysis and empathetic listening.' },
      { number: '02', title: 'Plan', description: 'Design a strategic roadmap combining AI, automation, and lean principles tailored to your unique challenges.' },
      { number: '03', title: 'Build', description: 'Implement solutions with agile methodology, ensuring continuous alignment with business objectives.' },
      { number: '04', title: 'Test & Refine', description: 'Rigorously test, measure KPIs, and iterate based on real-world feedback and data insights.' },
      { number: '05', title: 'Deliver', description: 'Deploy optimized workflows and empower teams with training, documentation, and ongoing support.' },
    ],
  },
  expertise: {
    title: 'Expertise & Certifications',
    subtitle: 'Core competencies and professional certifications.',
    skills: [
      { name: 'AI in Operations', level: 95, category: 'Technology' },
      { name: 'Customer Experience (CX)', level: 98, category: 'Leadership' },
      { name: 'Lean Six Sigma', level: 92, category: 'Methodology' },
      { name: 'M365 Copilot & Power Platform', level: 90, category: 'Technology' },
      { name: 'Process Automation (RPA)', level: 88, category: 'Technology' },
      { name: 'Workforce Management', level: 95, category: 'Operations' },
      { name: 'Data Analytics & BI', level: 85, category: 'Technology' },
      { name: 'Change Management', level: 93, category: 'Leadership' },
      { name: 'Stakeholder Engagement', level: 96, category: 'Leadership' },
      { name: 'Training & Development', level: 90, category: 'Leadership' },
    ],
    badges: [
      { name: 'Thinkers360 Top 100 Thought Leader: Agile', image: '/certificates/thinkers360-agile.png', link: 'https://www.thinkers360.com/tl/AbhishekShuklaCXandAILeader' },
      { name: 'Thinkers360 Certified Expert: Leadership', image: '/certificates/thinkers360-leadership.png', link: 'https://www.thinkers360.com/tl/AbhishekShuklaCXandAILeader' },
    ],
    certifications: [
      { name: 'The AI-Driven Project Manager', image: '/certificates/linkedin-learning.jpg' },
      { name: 'Effective Leadership - HP LIFE', image: '/certificates/hp-life.jpg' },
      { name: 'Knowledge Management Systems and Customer Analytics - IBM', image: '/certificates/ibm-skillsbuild.jpg' },
      { name: 'Lean Six Sigma White Belt', image: '/certificates/lean-six-sigma.jpg' },
    ],
  },
  contact: {
    title: 'Let\'s Connect',
    subtitle: 'Ready to optimize your business operations or accelerate your career track? Reach out directly to schedule your primary consultation strategy session today.',
    cta: 'Get In Touch',
  },
  books: {
    title: 'Publications',
    items: [
      {
        title: 'The Bridge You Become: Becoming the Leader Others Remember',
        description: 'A transformative guide on leadership, blending deep human insights with actionable operational strategies. Discover how to build bridges between your potential and your team\'s success.',
        link: 'https://a.co/d/07fJjZRe',
        image: '/book-cover.png',
      }
    ]
  },
  navLinks: [
    { label: 'About', href: '#about' },
    { label: 'Services', href: '#work' },
    { label: 'Process', href: '#process' },
    { label: 'Expertise', href: '#expertise' },
    { label: 'Books', href: '#books' },
    { label: 'Contact', href: '#contact' },
  ],
} as const;
