export const siteConfig = {
  name: 'Abhishek Shukla',
  title: 'CX & AI Leader | Consultant | Author',
  tagline: 'Helping organizations improve customer experience, transform operations and adopt AI, while helping professionals prepare for the future of work.',
  bio: 'I work at the intersection of Customer Experience, AI, Business Operations and Leadership, turning real-world challenges into practical strategies and solutions.',
  email: 'abhishekshukla16102000@gmail.com',
  phone: '8860220070',
  location: 'Delhi, India (Available Globally)',
  domain: 'abhishekshukla.com',
  resumeUrl: '/Abhishek_Shukla_Resume.pdf',
  profileImage: '/profile_main.png',
  social: {
    linkedin: 'https://linkedin.com/in/abhishek-shukla-cx',
    twitter: 'https://x.com/Abhishek1610200',
    instagram: 'https://www.instagram.com/cxai.leader?igsh=ZzUzMDNod3l3cTRq',
    youtube: 'https://www.youtube.com/@CXAILeader',
    thinkers360: 'https://www.thinkers360.com/tl/AbhishekShuklaCXandAILeader',
    freelancer: 'https://www.freelancer.com/u/abhishekshukla',
    jobbers: 'https://www.jobbers.com/abhishekshukla',
    topmate: 'https://topmate.io/abhishek_shukla1610',
  },
  hero: {
    greeting: 'Hello, I\'m',
    name: 'Abhishek Shukla',
    subtitle: 'CX & AI Leader | Consultant | Author',
    description: 'Helping organizations improve customer experience, transform operations and adopt AI, while helping professionals prepare for the future of work.\n\nI work at the intersection of Customer Experience, AI, Business Operations and Leadership, turning real-world challenges into practical strategies and solutions.',
    cta1: { text: 'Work With Me', href: '#contact' },
    cta2: { text: 'Explore Services', href: '#work' },
  },
  about: {
    title: 'About Abhishek',
    paragraphs: [
      'THE FUTURE OF WORK IS HUMAN + AI',
      'AI is changing how businesses operate, how customers interact with companies and how professionals build their careers. I help organizations and professionals understand these changes and turn them into practical opportunities.',
      'I am Abhishek Shukla, a CX & AI leader, consultant and author focused on customer experience, artificial intelligence, business operations and human leadership.',
      'My goal is simple: Help organizations work better, leaders lead better, and professionals prepare for what comes next.'
    ],
    philosophy: 'Technology creates leverage. People create impact.',
    stats: [
      { label: 'Global Availability', value: '100%' },
      { label: 'CX & AI Focus', value: '100%' },
      { label: 'Human Leadership', value: '100%' },
      { label: 'Practical Solutions', value: '100%' },
    ],
  },
  work: {
    title: 'What I Do',
    subtitle: 'Services for organizations, professionals, leaders and teams.',
    items: [
      {
        title: 'CX Consulting',
        category: 'For Organizations',
        description: 'Improve customer journeys, service operations and customer experience.',
        tags: ['Customer Journeys', 'Service Operations'],
        link: '#',
        icon: 'Users',
      },
      {
        title: 'AI Transformation',
        category: 'For Organizations',
        description: 'Identify practical AI opportunities across productivity, workflows and customer operations.',
        tags: ['Productivity', 'Workflows'],
        link: '#',
        icon: 'Cpu',
      },
      {
        title: 'Operations & Process Improvement',
        category: 'For Organizations',
        description: 'Optimize processes, workflows and operational performance.',
        tags: ['Workflows', 'Performance'],
        link: '#',
        icon: 'Settings',
      },
      {
        title: 'Leadership Advisory',
        category: 'For Organizations',
        description: 'Help leaders build stronger teams, communication, accountability and change capabilities.',
        tags: ['Team Building', 'Accountability'],
        link: '#',
        icon: 'Award',
      },
      {
        title: 'Data & Analytics',
        category: 'For Organizations',
        description: 'Turn operational data into clearer insights and better decisions.',
        tags: ['Insights', 'Decisions'],
        link: '#',
        icon: 'BarChart',
      },
      {
        title: 'Career Strategy',
        category: 'For Professionals & Candidates',
        description: 'Build a clearer direction for your next career move.',
        tags: ['Career Move', 'Direction'],
        link: '#',
        icon: 'Compass',
      },
      {
        title: 'Interview Preparation',
        category: 'For Professionals & Candidates',
        description: 'Prepare for leadership, behavioral and scenario-based interviews.',
        tags: ['Behavioral', 'Scenario-based'],
        link: '#',
        icon: 'Mic',
      },
      {
        title: 'Professional Positioning',
        category: 'For Professionals & Candidates',
        description: 'Strengthen your LinkedIn, resume, personal brand and professional story.',
        tags: ['LinkedIn', 'Resume'],
        link: '#',
        icon: 'UserCheck',
      },
      {
        title: 'AI Career Readiness',
        category: 'For Professionals & Candidates',
        description: 'Understand how AI is changing your role and the skills you need for the future.',
        tags: ['AI Skills', 'Future of Work'],
        link: '#',
        icon: 'Cpu',
      },
      {
        title: 'Leadership in an AI-Driven Workplace',
        category: 'For Leaders & Teams',
        description: 'Modern leadership requires both human judgment and technology awareness. I help leaders and teams navigate AI adoption, change, communication, accountability, customer-centric leadership and operational challenges.',
        tags: ['Change', 'Communication'],
        link: '#',
        icon: 'Users',
      }
    ],
  },
  process: {
    title: 'My Approach',
    subtitle: 'I focus on practical solutions built around the real challenge, not one-size-fits-all advice.',
    steps: [
      { number: '01', title: 'Discover', description: 'Understand the real challenge and context.' },
      { number: '02', title: 'Diagnose', description: 'Analyze root causes and identify opportunities.' },
      { number: '03', title: 'Design', description: 'Create practical strategies and solutions.' },
      { number: '04', title: 'Implement', description: 'Put solutions into action effectively.' },
      { number: '05', title: 'Improve', description: 'Measure results and refine for sustained impact.' },
    ],
  },
  expertise: {
    title: 'Why Work With Me',
    subtitle: 'From improving customer experience to adopting AI or preparing for the next career opportunity, I help people and organizations move forward.',
    skills: [
      { name: 'Real-World Experience', level: 100, category: 'Practical experience across CX, operations and leadership.' },
      { name: 'Business + People', level: 100, category: 'I consider both business outcomes and the people responsible for delivering them.' },
      { name: 'Practical AI', level: 100, category: 'AI focused on real workplace problems and opportunities.' },
      { name: 'Human-Centered Leadership', level: 100, category: 'Technology creates leverage. People create impact.' },
      { name: 'Companies & Startups', level: 100, category: 'Who I Work With' },
      { name: 'Leaders & Teams', level: 100, category: 'Who I Work With' },
      { name: 'Professionals & Candidates', level: 100, category: 'Who I Work With' },
    ],
    badges: [],
    certifications: [],
  },
  contact: {
    title: 'Global Consulting',
    subtitle: 'Working With Organizations & Professionals Worldwide. Based in India and available globally through remote consulting, advisory, workshops and project-based engagements. Let\'s build what\'s next - start with the challenge.',
    cta: 'Start a Conversation',
  },
  books: {
    title: 'Insights',
    items: [
      {
        title: 'CX. AI. Leadership. Future of Work.',
        description: 'Practical ideas, experiences and frameworks from my work and learning.',
        link: 'https://linkedin.com/in/abhishek-shukla-cx', // Defaulting to LinkedIn
        image: '/book-cover.png', // Keep a placeholder
      }
    ]
  },
  navLinks: [
    { label: 'About', href: '#about' },
    { label: 'Services', href: '#work' },
    { label: 'Approach', href: '#process' },
    { label: 'Why Me', href: '#expertise' },
    { label: 'Insights', href: '#books' },
    { label: 'Contact', href: '#contact' },
  ],
} as const;
